---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-mysql-fuse
    provider: jkube
    version: "1.0"
    group: com.redhat.training.openshift.hello
  name: kafka-mysql-fuse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-mysql-fuse
      provider: jkube
      group: com.redhat.camel.kafka.kafkamysql
  template:
    metadata:
      labels:
        app: kafka-mysql-fuse
        provider: jkube
        version: "1.0"
        group: com.redhat.camel.kafka.kafkamysql
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: kafka-mysql:latest
          imagePullPolicy: Always
          name: kafka-mysql-fuse
          ports:
            - containerPort: 8090
              name: http
              protocol: TCP
          securityContext:
            privileged: false